/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppAmbientesRouteImport } from './routes/_app/ambientes'
import { Route as AppChangePasswordRouteImport } from './routes/_app/change-password'
import { Route as AppConversationsRouteImport } from './routes/_app/conversations'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppImportAtaRouteImport } from './routes/_app/import-ata'
import { Route as AppMeetingsRouteImport } from './routes/_app/meetings'
import { Route as AppMuralRouteImport } from './routes/_app/mural'
import { Route as AppObligationsRouteImport } from './routes/_app/obligations'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppTrashRouteImport } from './routes/_app/trash'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks.index'
import { Route as AppTasksCalendarRouteImport } from './routes/_app/tasks.calendar'
import { Route as AppTasksKanbanRouteImport } from './routes/_app/tasks.kanban'
import { Route as AppTasksListRouteImport } from './routes/_app/tasks.list'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAmbientesRoute = AppAmbientesRouteImport.update({
  id: '/ambientes',
  path: '/ambientes',
  getParentRoute: () => AppRoute,
} as any)
const AppChangePasswordRoute = AppChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppImportAtaRoute = AppImportAtaRouteImport.update({
  id: '/import-ata',
  path: '/import-ata',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppMuralRoute = AppMuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => AppRoute,
} as any)
const AppObligationsRoute = AppObligationsRouteImport.update({
  id: '/obligations',
  path: '/obligations',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppTasksCalendarRoute = AppTasksCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppTasksKanbanRoute = AppTasksKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppTasksListRoute = AppTasksListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppTasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AppAgendaRoute
  '/ambientes': typeof AppAmbientesRoute
  '/change-password': typeof AppChangePasswordRoute
  '/conversations': typeof AppConversationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/import-ata': typeof AppImportAtaRoute
  '/meetings': typeof AppMeetingsRoute
  '/mural': typeof AppMuralRoute
  '/obligations': typeof AppObligationsRoute
  '/reports': typeof AppReportsRoute
  '/requests': typeof AppRequestsRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/trash': typeof AppTrashRoute
  '/users': typeof AppUsersRoute
  '/tasks/calendar': typeof AppTasksCalendarRoute
  '/tasks/kanban': typeof AppTasksKanbanRoute
  '/tasks/list': typeof AppTasksListRoute
  '/tasks/': typeof AppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AppAgendaRoute
  '/ambientes': typeof AppAmbientesRoute
  '/change-password': typeof AppChangePasswordRoute
  '/conversations': typeof AppConversationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/import-ata': typeof AppImportAtaRoute
  '/meetings': typeof AppMeetingsRoute
  '/mural': typeof AppMuralRoute
  '/obligations': typeof AppObligationsRoute
  '/reports': typeof AppReportsRoute
  '/requests': typeof AppRequestsRoute
  '/settings': typeof AppSettingsRoute
  '/trash': typeof AppTrashRoute
  '/users': typeof AppUsersRoute
  '/tasks/calendar': typeof AppTasksCalendarRoute
  '/tasks/kanban': typeof AppTasksKanbanRoute
  '/tasks/list': typeof AppTasksListRoute
  '/tasks': typeof AppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/ambientes': typeof AppAmbientesRoute
  '/_app/change-password': typeof AppChangePasswordRoute
  '/_app/conversations': typeof AppConversationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/import-ata': typeof AppImportAtaRoute
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/mural': typeof AppMuralRoute
  '/_app/obligations': typeof AppObligationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/requests': typeof AppRequestsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRouteWithChildren
  '/_app/trash': typeof AppTrashRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/tasks/calendar': typeof AppTasksCalendarRoute
  '/_app/tasks/kanban': typeof AppTasksKanbanRoute
  '/_app/tasks/list': typeof AppTasksListRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/ambientes'
    | '/change-password'
    | '/conversations'
    | '/dashboard'
    | '/import-ata'
    | '/meetings'
    | '/mural'
    | '/obligations'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/tasks'
    | '/trash'
    | '/users'
    | '/tasks/calendar'
    | '/tasks/kanban'
    | '/tasks/list'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/ambientes'
    | '/change-password'
    | '/conversations'
    | '/dashboard'
    | '/import-ata'
    | '/meetings'
    | '/mural'
    | '/obligations'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/trash'
    | '/users'
    | '/tasks/calendar'
    | '/tasks/kanban'
    | '/tasks/list'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/agenda'
    | '/_app/ambientes'
    | '/_app/change-password'
    | '/_app/conversations'
    | '/_app/dashboard'
    | '/_app/import-ata'
    | '/_app/meetings'
    | '/_app/mural'
    | '/_app/obligations'
    | '/_app/reports'
    | '/_app/requests'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/trash'
    | '/_app/users'
    | '/_app/tasks/calendar'
    | '/_app/tasks/kanban'
    | '/_app/tasks/list'
    | '/_app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ambientes': {
      id: '/_app/ambientes'
      path: '/ambientes'
      fullPath: '/ambientes'
      preLoaderRoute: typeof AppAmbientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/change-password': {
      id: '/_app/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AppChangePasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations': {
      id: '/_app/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import-ata': {
      id: '/_app/import-ata'
      path: '/import-ata'
      fullPath: '/import-ata'
      preLoaderRoute: typeof AppImportAtaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mural': {
      id: '/_app/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof AppMuralRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/obligations': {
      id: '/_app/obligations'
      path: '/obligations'
      fullPath: '/obligations'
      preLoaderRoute: typeof AppObligationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/tasks/calendar': {
      id: '/_app/tasks/calendar'
      path: '/calendar'
      fullPath: '/tasks/calendar'
      preLoaderRoute: typeof AppTasksCalendarRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/tasks/kanban': {
      id: '/_app/tasks/kanban'
      path: '/kanban'
      fullPath: '/tasks/kanban'
      preLoaderRoute: typeof AppTasksKanbanRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/tasks/list': {
      id: '/_app/tasks/list'
      path: '/list'
      fullPath: '/tasks/list'
      preLoaderRoute: typeof AppTasksListRouteImport
      parentRoute: typeof AppTasksRoute
    }
  }
}

interface AppTasksRouteChildren {
  AppTasksCalendarRoute: typeof AppTasksCalendarRoute
  AppTasksKanbanRoute: typeof AppTasksKanbanRoute
  AppTasksListRoute: typeof AppTasksListRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksCalendarRoute: AppTasksCalendarRoute,
  AppTasksKanbanRoute: AppTasksKanbanRoute,
  AppTasksListRoute: AppTasksListRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppAmbientesRoute: typeof AppAmbientesRoute
  AppChangePasswordRoute: typeof AppChangePasswordRoute
  AppConversationsRoute: typeof AppConversationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppImportAtaRoute: typeof AppImportAtaRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppMuralRoute: typeof AppMuralRoute
  AppObligationsRoute: typeof AppObligationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppTrashRoute: typeof AppTrashRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppAmbientesRoute: AppAmbientesRoute,
  AppChangePasswordRoute: AppChangePasswordRoute,
  AppConversationsRoute: AppConversationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppImportAtaRoute: AppImportAtaRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppMuralRoute: AppMuralRoute,
  AppObligationsRoute: AppObligationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppTrashRoute: AppTrashRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
